In [11]:
import pandas as pd

# 读取原始数据
df = pd.read_csv('../data/raw/games_raw.csv')

cols_to_drop = ['img', 'last_update', 'title','na_sales','jp_sales','pal_sales','other_sales']
df.drop(columns=cols_to_drop, inplace=True)

df.dropna(subset=['critic_score'],inplace = True)

for i in df.columns:
        
    df.dropna(subset=[i],inplace = True)
    

save_road='../data/processed/data_processed.csv'
df.to_csv(save_road,index=False)

df.info()

<class 'pandas.DataFrame'>
Index: 4123 entries, 0 to 18919
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   console       4123 non-null   str
 1   genre         4123 non-null   str
 2   publisher     4123 non-null   str
 3   developer     4123 non-null   str
 4   critic_score  4123 non-null   float64
 5   total_sales   4123 non-null   float64
 6   release_date  4123 non-null   str
dtypes: float64(2), str(5)
memory usage: 257.7 KB

In [14]:

df = pd.read_csv('../data/processed/data_processed.csv')

# 先转换为 datetime 类型，指定格式（dayfirst=True 表示日在前）
df['release_date'] = pd.to_datetime(df['release_date'], format='%d-%m-%Y', errors='coerce')

df.head()

,console,genre,publisher,developer,critic_score,total_sales,release_date
0,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,2013-09-17
1,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,2014-11-18
2,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,2002-10-28
4,PS4,Shooter,Activision,Treyarch,8.1,15.09,2015-11-06
5,X360,Shooter,Activision,Infinity Ward,8.7,14.82,2011-11-08

In [15]:
df['release_date'].max()

Timestamp('2023-10-11 00:00:00')

In [16]:
# 获取当前日期（仅日期部分，忽略时间）
ddl = pd.Timestamp('2024-01-01')
ddl

Timestamp('2024-01-01 00:00:00')

In [17]:

# 计算距今天数（单位：天）
df['days_since_release'] = (ddl - df['release_date']).dt.days

df.head()

,console,genre,publisher,developer,critic_score,total_sales,release_date,days_since_release
0,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,2013-09-17,3758.0
1,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,2014-11-18,3331.0
2,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,2002-10-28,7735.0
4,PS4,Shooter,Activision,Treyarch,8.1,15.09,2015-11-06,2978.0
5,X360,Shooter,Activision,Infinity Ward,8.7,14.82,2011-11-08,4437.0

In [18]:
df.drop(columns='release_date',inplace=True)
df.head()

,console,genre,publisher,developer,critic_score,total_sales,days_since_release
0,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,3758.0
1,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,3331.0
2,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,7735.0
4,PS4,Shooter,Activision,Treyarch,8.1,15.09,2978.0
5,X360,Shooter,Activision,Infinity Ward,8.7,14.82,4437.0

In [19]:
# 对多个列
cat_cols = ['console', 'genre', 'publisher', 'developer']
for col in cat_cols:
    df[f'{col}_code'] = df[col].astype('category').cat.codes
df.head()

,console,genre,publisher,developer,critic_score,total_sales,days_since_release,console_code,genre_code,publisher_code,developer_code
0,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,3758.0,20,0,311,1128
1,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,3331.0,21,0,311,1128
2,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,7735.0,19,0,311,1128
4,PS4,Shooter,Activision,Treyarch,8.1,15.09,2978.0,21,15,17,1415
5,X360,Shooter,Activision,Infinity Ward,8.7,14.82,4437.0,33,15,17,659

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 6678 entries, 0 to 63999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   console             6678 non-null   str
 1   genre               6678 non-null   str
 2   publisher           6678 non-null   str
 3   developer           6678 non-null   str
 4   critic_score        6678 non-null   float64
 5   total_sales         4126 non-null   float64
 6   days_since_release  6634 non-null   float64
 7   console_code        6678 non-null   int8
 8   genre_code          6678 non-null   int8
 9   publisher_code      6678 non-null   int16
 10  developer_code      6678 non-null   int16
dtypes: float64(3), int16(2), int8(2), str(4)
memory usage: 456.5 KB

In [21]:
df.dropna(subset=['days_since_release'],inplace = True)

In [22]:
df.dropna(subset=['total_sales'],inplace = True)

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 4123 entries, 0 to 18919
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   console             4123 non-null   str
 1   genre               4123 non-null   str
 2   publisher           4123 non-null   str
 3   developer           4123 non-null   str
 4   critic_score        4123 non-null   float64
 5   total_sales         4123 non-null   float64
 6   days_since_release  4123 non-null   float64
 7   console_code        4123 non-null   int8
 8   genre_code          4123 non-null   int8
 9   publisher_code      4123 non-null   int16
 10  developer_code      4123 non-null   int16
dtypes: float64(3), int16(2), int8(2), str(4)
memory usage: 281.8 KB

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [26]:
df.drop(columns=['console_code','genre_code','publisher_code','developer_code'],inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 4123 entries, 0 to 18919
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   console             4123 non-null   str
 1   genre               4123 non-null   str
 2   publisher           4123 non-null   str
 3   developer           4123 non-null   str
 4   critic_score        4123 non-null   float64
 5   total_sales         4123 non-null   float64
 6   days_since_release  4123 non-null   float64
dtypes: float64(3), str(4)
memory usage: 257.7 KB

In [28]:
df.describe(include='all')

,console,genre,publisher,developer,critic_score,total_sales,days_since_release
count,4123,4123,4123,4123,4123.000000,4123.000000,4123.000000
unique,28,20,214,1050,NaN,NaN,NaN
top,X360,Action,Electronic Arts,EA Canada,NaN,NaN,NaN
freq,592,732,338,99,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,7.101819,0.737747,5887.476837
std,NaN,NaN,NaN,NaN,1.439631,1.408878,1731.841475
min,NaN,NaN,NaN,NaN,1.000000,0.000000,1096.000000
25%,NaN,NaN,NaN,NaN,6.300000,0.110000,4822.000000
50%,NaN,NaN,NaN,NaN,7.300000,0.300000,5760.000000
75%,NaN,NaN,NaN,NaN,8.100000,0.750000,7006.000000
max,NaN,NaN,NaN,NaN,10.000000,20.320000,12632.000000

In [29]:
from catboost import CatBoostRegressor, Pool

In [31]:
# 定义特征列和目标列
features = ['console', 'genre', 'publisher', 'developer', 'total_sales', 'days_since_release']
target = 'critic_score'

X = df[features]
y = df[target]

print(type(X))

<class 'pandas.DataFrame'>

In [32]:
X

,console,genre,publisher,developer,total_sales,days_since_release
0,PS3,Action,Rockstar Games,Rockstar North,20.32,3758.0
1,PS4,Action,Rockstar Games,Rockstar North,19.39,3331.0
2,PS2,Action,Rockstar Games,Rockstar North,16.15,7735.0
4,PS4,Shooter,Activision,Treyarch,15.09,2978.0
5,X360,Shooter,Activision,Infinity Ward,14.82,4437.0
...,...,...,...,...,...,...
18895,PC,Role-Playing,Ubisoft,Arkane Studios / Floodgate Entertainment / Kuj...,0.00,6278.0
18907,PC,Role-Playing,2K Games,BioWare Corp.,0.00,6153.0
18917,WiiU,Platform,Rain Games,Rain Games,0.00,3399.0
18918,XB,Platform,Ubisoft,Ubisoft Montreal,0.00,6313.0
18919,PC,Platform,THQ,Heavy Iron Studios,0.00,7005.0

In [37]:
# 获取所有字符串类型的列名
categorical_features = X.select_dtypes(include=['object', 'string']).columns.tolist()

In [38]:
categorical_features

['console', 'genre', 'publisher', 'developer']

In [48]:
import numpy as np

In [62]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.05, random_state=42
)

In [63]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 3916 entries, 1730 to 1726
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   console             3916 non-null   str
 1   genre               3916 non-null   str
 2   publisher           3916 non-null   str
 3   developer           3916 non-null   str
 4   total_sales         3916 non-null   float64
 5   days_since_release  3916 non-null   float64
dtypes: float64(2), str(4)
memory usage: 214.2 KB

In [70]:
model = CatBoostRegressor(
    iterations=1500,           # 树的数量（迭代次数）
    learning_rate=0.05,       # 学习率
    depth=8,                  # 树的深度
    loss_function='RMSE',     # 回归任务常用 RMSE
    cat_features=categorical_features,  # 传入类别特征
    verbose=100,              # 每100轮输出一次日志
    early_stopping_rounds=100  # 早停，防止过拟合
)

# 训练模型（使用 Pool 不是必须的，但可以更方便地传递参数）
model.fit(X_train, y_train, eval_set=(X_test, y_test))

0:	learn: 1.4286173	test: 1.3826262	best: 1.3826262 (0)	total: 24.9ms	remaining: 37.4s
100:	learn: 1.0962888	test: 1.0330744	best: 1.0330744 (100)	total: 2.42s	remaining: 33.6s
200:	learn: 1.0060352	test: 1.0213559	best: 1.0213559 (200)	total: 4.79s	remaining: 31s
300:	learn: 0.9262289	test: 1.0234042	best: 1.0190577 (205)	total: 7.2s	remaining: 28.7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.019057741
bestIteration = 205

Shrink model to first 206 iterations.

CatBoostRegressor(cat_features=['console', 'genre', 'publisher', 'developer'], depth=8, early_stopping_rounds=100, iterations=1500, learning_rate=0.05, loss_function='RMSE', verbose=100)

In [71]:
y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")

RMSE: 1.0191
MAE: 0.7802